version: "3.8"
services:

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - php
      - mongo
    links:
      - php

  php:
    build: ./php
    command: sh -c "composer config extra.symfony.allow-contrib true ; chmod -R 777 var ; composer install ; php-fpm"
    restart: always
    expose:
      - "9000"
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
